/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package grafiktanpajfreechart;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Arc2D;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RectangularShape;
import javax.swing.JOptionPane;

/**
 *
 * @author traspac
 */
public class PanelDoughnoutChart extends javax.swing.JPanel {

    String[] matkul = {
        "KOMPUTER GRAFIK", 
        "BASIS DATA", 
        "REKAYASA PERANGKAT LUNAK", 
        "AUTOMATA", 
        "PEMROGRAMAN JAVA",
        "ALGORITMA DASAR"
    };
    int[] nilai = {85, 60, 75, 50, 25, 40};
    Color[] warna = {Color.BLUE, Color.RED,Color.GREEN, Color.MAGENTA, Color.ORANGE, Color.DARK_GRAY};
    /**
     * Creates new form PanelDoughnoutChart
     */
    public PanelDoughnoutChart() {
        initComponents();
        
        this.setPreferredSize(new Dimension(600, 400));
        this.setBackground(Color.white);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        Graphics2D g2 = (Graphics2D) g;
        
        // antialias agar hasil bagus
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        // hitung total
        float total = 0.0f;
        for (int k = 0; k < nilai.length; k++) 
            total += nilai[k];
                    
        // hitung presentase tiap-tiap sektor
        float sudut, awal = 90;
        float lx = 350, ly = 70, lw = 10, lh = 10;
        for(int k = 0; k < nilai.length; k++){
            // hitung besarnya sudut tiap tiap sektor
            sudut = 360.0f * nilai[k] / total;
            RectangularShape sektor =  new Arc2D.Float(70, 30, 250, 250, awal, sudut, Arc2D.PIE);
            
            g2.setColor(warna[k]);
            g2.fill(sektor);
            awal += sudut;
            
            // tampilan ketarangan matkul
            g2.fill(new Rectangle2D.Float(lx, ly, lw, lh));
            g2.setColor(Color.black);
            g2.drawString(matkul[k], lx+lw+5, ly + lh);
            ly += (lh + 5);
            
            g2.setColor(Color.white);
            g2.fillOval(157, 122, 70, 70);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
